baseURL = 'https://ferza17.github.io/ferza-me/'
languageCode = 'en-us'
title = 'Fery Reza Aditya'
theme = 'hugo-PaperMod'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3