name: Publish to GitHub Pages

on:
  push:
    branches:
      - main  # The branch that triggers the workflow
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source files
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true # Checkout submodules if any

      # Step 2: Checkout the gh-pages branch to upload the built site
      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages # Deploy branch
          path: built-site # Deploy output directory

      # Step 3: Setup Hugo (download and extract)
      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      # Step 4: Build the Hugo static site
      - name: Build
        run: ${RUNNER_TEMP}/hugo --minify # Builds with minification for performance

      # Step 5: Deploy to GitHub Pages
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/ # Copy generated files to the deploy directory
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'Ferza17' # Replace with your GitHub username
          git config user.email 'feryreza85@gmail.com'   # Replace with your GitHub email
          git commit -m 'Updated site' || echo "No changes to commit"
          git push