name: Publish to GitHub Pages

on:
  push:
    branches:
      - main  # The branch that triggers the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository with submodules
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true  # Include submodules (theme)

      # Step 2: Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Build the site
      - name: Build Hugo
        run: hugo --minify

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public